### PR TITLE
Add YOG precipitation to diagnostics and coupler

### LINKED ISSUE #24: Need to pass precipitation from YOG scheme to coupler
Currently yog_prec is diagnosed and output but I don't think it is added to the surface water fluxes used by the coupler (e.g. would be needed by land or ocean parts of model).

CAM puts precipitation into either large-scale (precl) or convective (precc). In principle, yog could contribute to both. But for now we are considering yog to be a convection scheme, so one option would be to add yog_prec to precc in cam_diagnostics.f90 here:

https://github.com/m2lines/CAM-ML/blob/facd0cee74a7c4017501d49e9d51221fc875df8b/src/physics/cam/cam_diagnostics.F90#L1577C7-L1586C13

Then my reading of CAM is that precc gets passed to the coupler here:

https://github.com/m2lines/CAM-ML/blob/facd0cee74a7c4017501d49e9d51221fc875df8b/src/cpl/atm_import_export.F90#L240

### PR DESCRIPTION
**Pull request by jatkinson1000**
This will close #24 

`cam_diagnostics.F90` has been modified to fetch the output of `PREC_YOG` from the buffer and add it to the `precc` component that is then used for total convective precipitation diagnostic and convection.

`precc` is also passed to the coupler to land/ocean, so this means that the YOG precipitation will be included there as well.

At present it feels there is a bit of a 'special treatment' of YOG, so review and advice from @judithberner about whether we have approached this in the most appropriate way, and any suggestions for modification would be appreciated.

Marking as WIP as review and discussion definitely required.

### CODE REVIEW

**Comment by jatkinson1000** [comment]
For coupler need to add to `cam_out%precc` see code reference in #24 
Trace back and see where we set this value, and then add YOG_prec there.

**Comment by jatkinson1000** [comment]
Notes following ZM:

- `YOG_PREC` is a diagnostic output, similar to `PRECZ` in ZM scheme
- in ZM `PREC_DP` is pulled from the physics buffer (into a pointer) and passed to zm tendency scheme (and then `zm_convr()`).
  - here it is zeroed (for `ncol`) and then assigned values.
  - It is then assigned to the PRECZ diagnostic output at the end of the scheme.
- Once ZM has completed `PREC_DP` is used in physpkg to check energy integrals
- `PREC_DP` is then fetched from the physics buffer in `camsrfexch.F90` to be added to `cam_out%precc`

**Comment by jatkinson1000** [comment]
My suggestion is to do the following:

- pull `PREC_DP` from the physics buffer in `yog_tend` - NB BE CAREFUL WITH PCOL vs NCOL
- add `yog_prec` to `PREC_DP` at the end of `yog_tend`
- add `flx_cnd` to the energy check after `yog_tend` in `physpkg.F90`
  - Note question here - do we want to use `prec_dp`, or only the change due to YOG\
    Answering this may involve making YOG mutually exclusing to ZM and other schemes, zeroing `prec_dp` or modifying
    to add a new variable.

This way the precipitation will be automatically included in the `cam_out%precc` passed to the coupler (and `PRECC` diagnostic output).

There are useful discussion points that should be had before we merge this.

**Comment by jatkinson1000** [comment]
In https://github.com/m2lines/CAM-ML/pull/35/commits/3762aa28492aa013a53f9f26d426dddd45cd4f15 we add the precipitation from YOG to the energy checker.

However, if for some reason users were running both YOG and ZM the value from `prec_dp` used would be precipitation from both schemes, not just one.

Do we want to try and implement some safeguards or adjust permissable configurations?

**Comment by jatkinson1000** [comment]
prec_cpl

Attached image shows a test with the coupled code using Toga II.

Breaking this down:

- previously PRECC output as 0 (magenta) as not coupled.
- Now precc output as equal to YOGPREC + PRECL

**Review by MarionBWeinzierl — APPROVED** [review]
This looks good to me, and seems to do what it should (according to your graphs). A couple more comments in the code would be helpful, but not crucial for this to be merged.

**Review by omarjamil — APPROVED** [review]

**Pull request merged**
